[2023-10-15 10:05:13,060: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 10:05:13,103: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:05:13,145: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:05:13,153: INFO: common: created directory at: artifacts]
[2023-10-15 10:05:13,170: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 10:05:19,540: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 9982:15F91D:44413:82C62:652B6C00
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 04:35:15 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100021-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1697344514.170096,VS0,VE922
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ad25a8b88f0184e9c5ccabef01c6c490d23a06ff
Expires: Sun, 15 Oct 2023 04:40:15 GMT
Source-Age: 1

]
[2023-10-15 10:05:21,662: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 10:05:21,662: INFO: main: *******************]
[2023-10-15 10:05:21,662: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 10:05:21,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:05:21,695: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:05:21,721: INFO: common: created directory at: artifacts]
[2023-10-15 10:05:21,747: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 10:05:25,144: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 10:05:28,029: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 10:05:28,029: INFO: main: *******************]
[2023-10-15 10:05:28,029: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 10:05:28,029: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:05:28,045: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:05:28,045: INFO: common: created directory at: artifacts]
[2023-10-15 10:05:28,061: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 10:05:28,070: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 10:05:28,075: ERROR: main: 'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "C:\ML Projects\Chicken-Disease-Classification-Projects\main.py", line 40, in <module>
    model_trainer.main()
  File "c:\ml projects\chicken-disease-classification-projects\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ml projects\chicken-disease-classification-projects\src\cnnClassifier\components\prepare_callbacks.py", line 36, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\ml projects\chicken-disease-classification-projects\src\cnnClassifier\components\prepare_callbacks.py", line 27, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-10-15 10:34:10,927: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:34:10,967: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:34:10,975: INFO: common: created directory at: artifacts]
[2023-10-15 10:34:10,983: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 10:34:10,991: INFO: 1170291011: File already exists of size: ~ 11345 KB]
[2023-10-15 10:36:41,911: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:36:41,927: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:36:41,927: INFO: common: created directory at: artifacts]
[2023-10-15 10:36:41,935: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 10:36:45,804: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 10:38:03,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:38:03,511: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:38:03,519: INFO: common: created directory at: artifacts]
[2023-10-15 10:38:03,527: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 10:38:03,535: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 10:47:11,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:47:11,549: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:47:11,555: INFO: common: created directory at: artifacts]
[2023-10-15 10:47:11,555: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 10:47:11,563: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 10:47:30,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:47:30,546: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:47:30,546: INFO: common: created directory at: artifacts]
[2023-10-15 10:47:30,554: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 10:47:30,562: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 10:53:31,164: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 10:53:31,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:53:31,188: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:53:31,188: INFO: common: created directory at: artifacts]
[2023-10-15 10:53:31,188: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 10:53:31,196: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2023-10-15 10:53:34,087: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 10:53:34,087: INFO: main: *******************]
[2023-10-15 10:53:34,087: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 10:53:34,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:53:34,102: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:53:34,102: INFO: common: created directory at: artifacts]
[2023-10-15 10:53:34,102: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 10:53:37,183: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 10:53:40,648: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 10:53:40,648: INFO: main: *******************]
[2023-10-15 10:53:40,648: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 10:53:40,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 10:53:40,666: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 10:53:40,666: INFO: common: created directory at: artifacts]
[2023-10-15 10:53:40,666: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 10:53:40,674: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 10:53:40,682: INFO: common: created directory at: artifacts\training]
[2023-10-15 11:01:49,144: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-10-15 11:01:49,160: INFO: main: *******************]
[2023-10-15 11:01:49,160: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-10-15 11:01:49,277: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:01:49,297: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:01:49,313: INFO: common: created directory at: artifacts]
[2023-10-15 11:04:25,443: INFO: common: json file saved at: scores.json]
[2023-10-15 11:04:25,443: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-10-15 11:17:52,249: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 11:17:52,257: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 11:18:19,874: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 11:18:19] "GET / HTTP/1.1" 200 -]
[2023-10-15 11:20:09,375: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 11:20:09] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 11:22:18,241: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 11:22:18,259: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:22:18,278: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:22:18,278: INFO: common: created directory at: artifacts]
[2023-10-15 11:22:18,286: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 11:22:19,711: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Sun, 15 Oct 2023 05:52:19 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=511=BrPqwRG5xX1CfOp-twLYE3QfT7pFfaFoSXmlrvlehNN_DRvGrM0duQtTPfxM6oso10Vi2IZxEq5RR4nvz5Jp3oXveNKUbuO4CrXNKOvJ2mM09MlQp6U70vFlKcB5BubroErmTLbRW4VUPBpxYyY41TY2hcQTwz-JynHfLJym6ro; expires=Mon, 15-Apr-2024 05:52:19 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2023-10-15 11:22:20,358: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\ML Projects\Chicken-Disease-Classification-Projects\main.py", line 12, in <module>
    data_ingestion.main()
  File "c:\ml projects\chicken-disease-classification-projects\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\ml projects\chicken-disease-classification-projects\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1299, in __init__
    self._RealGetContents()
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1366, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-10-15 11:41:17,687: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 11:41:17,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:41:17,735: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:41:17,743: INFO: common: created directory at: artifacts]
[2023-10-15 11:41:17,751: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 11:41:17,759: INFO: data_ingestion: File already exists of size: ~ 82 KB]
[2023-10-15 11:41:17,782: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1299, in __init__
    self._RealGetContents()
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1366, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-10-15 11:43:38,108: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 11:43:38,117: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:43:38,124: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:43:38,124: INFO: common: created directory at: artifacts]
[2023-10-15 11:43:38,134: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 11:43:38,136: INFO: data_ingestion: File already exists of size: ~ 82 KB]
[2023-10-15 11:43:38,144: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1299, in __init__
    self._RealGetContents()
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1366, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-10-15 11:49:40,525: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 11:49:40,552: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:49:40,560: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:49:40,568: INFO: common: created directory at: artifacts]
[2023-10-15 11:49:40,568: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 11:49:40,576: INFO: data_ingestion: File already exists of size: ~ 82 KB]
[2023-10-15 11:49:40,593: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\main.py", line 12, in <module>
    data_ingestion.main()
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1299, in __init__
    self._RealGetContents()
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\zipfile.py", line 1366, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-10-15 12:07:51,128: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:07:51,158: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:07:51,158: INFO: common: created directory at: artifacts]
[2023-10-15 12:07:51,166: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 12:07:57,802: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 12:09:11,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:09:11,424: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:09:11,424: INFO: common: created directory at: artifacts]
[2023-10-15 12:09:11,432: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:09:11,443: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:11:08,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:11:08,259: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:11:08,266: INFO: common: created directory at: artifacts]
[2023-10-15 12:11:08,274: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:11:08,274: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:13:17,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:13:17,403: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:13:17,411: INFO: common: created directory at: artifacts]
[2023-10-15 12:13:17,411: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:13:17,422: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:13:17,430: INFO: common: created directory at: artifacts\training]
[2023-10-15 12:13:23,582: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:13:23,590: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:13:23,590: INFO: common: created directory at: artifacts]
[2023-10-15 12:13:23,598: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:13:23,606: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:13:23,606: INFO: common: created directory at: artifacts\training]
[2023-10-15 12:15:08,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:15:08,578: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:15:08,586: INFO: common: created directory at: artifacts]
[2023-10-15 12:15:08,594: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:15:08,594: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:15:08,602: INFO: common: created directory at: artifacts\training]
[2023-10-15 12:23:02,402: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:23:02,427: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:23:02,456: INFO: common: created directory at: artifacts]
[2023-10-15 12:23:02,470: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:23:02,476: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:23:02,567: INFO: common: created directory at: artifacts\training]
[2023-10-15 12:26:35,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:26:35,574: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:26:35,580: INFO: common: created directory at: artifacts]
[2023-10-15 12:26:35,586: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 12:26:46,553: INFO: 1170291011: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7D5A:D8C7B:BEE31:14EB29:652B8D23
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 06:56:38 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100031-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1697352997.826741,VS0,VE1281
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: be32b5535950a26695644201432d6d72781223d4
Expires: Sun, 15 Oct 2023 07:01:38 GMT
Source-Age: 1

]
[2023-10-15 12:28:19,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:28:19,304: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:28:19,309: INFO: common: created directory at: artifacts]
[2023-10-15 12:28:19,319: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 12:28:24,066: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:28:24,081: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:28:24,086: INFO: common: created directory at: artifacts]
[2023-10-15 12:28:24,099: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:28:24,106: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:28:24,845: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 12:29:22,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:29:22,930: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:29:22,944: INFO: common: created directory at: artifacts]
[2023-10-15 12:29:22,959: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 12:29:22,966: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 12:29:23,087: INFO: common: created directory at: artifacts\training]
[2023-10-15 12:58:58,729: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:58:58,741: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:58:58,746: INFO: common: created directory at: artifacts]
[2023-10-15 13:00:00,638: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:00:00,647: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:00:00,655: INFO: common: created directory at: artifacts]
[2023-10-15 13:09:01,575: INFO: common: json file saved at: scores.json]
[2023-10-15 13:10:46,979: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 13:10:46,985: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:10:46,988: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:10:46,993: INFO: common: created directory at: artifacts]
[2023-10-15 13:10:46,993: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 13:10:46,998: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-15 13:10:53,253: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 13:10:53,263: INFO: main: *******************]
[2023-10-15 13:10:53,308: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 13:10:53,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:10:53,394: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:10:53,414: INFO: common: created directory at: artifacts]
[2023-10-15 13:10:53,444: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 13:10:56,919: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 13:11:00,186: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 13:11:00,191: INFO: main: *******************]
[2023-10-15 13:11:00,196: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 13:11:00,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:11:00,246: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:11:00,251: INFO: common: created directory at: artifacts]
[2023-10-15 13:11:00,251: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 13:11:00,261: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 13:11:00,301: INFO: common: created directory at: artifacts\training]
[2023-10-15 13:35:41,306: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-10-15 13:35:41,341: INFO: main: *******************]
[2023-10-15 13:35:41,341: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-10-15 13:35:41,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:35:41,637: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:35:41,647: INFO: common: created directory at: artifacts]
[2023-10-15 13:42:29,969: INFO: common: json file saved at: scores.json]
[2023-10-15 13:42:29,972: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-10-15 13:43:41,402: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 13:43:41,412: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 13:43:49,960: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:43:49] "GET / HTTP/1.1" 200 -]
[2023-10-15 13:45:14,779: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:45:14] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:46:43,045: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:46:43] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:46:54,773: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:46:54] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:47:39,370: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:47:39] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:47:55,724: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:47:55] "GET / HTTP/1.1" 200 -]
[2023-10-15 13:48:07,990: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002B0F8E68EA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-15 13:48:08,002: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:48:08] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:48:19,442: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002B0803B1800> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-15 13:48:19,457: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:48:19] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:50:45,841: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:50:45] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:52:52,753: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:52:52] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:53:11,422: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:53:11] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:54:25,291: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:54:25] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:55:07,016: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 13:55:07,021: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 13:55:13,918: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:55:13] "GET / HTTP/1.1" 200 -]
[2023-10-15 13:55:29,326: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:55:29] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:55:45,417: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:55:45] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:55:59,843: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:55:59] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:56:17,041: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:56:17] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:57:01,159: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:57:01] "GET / HTTP/1.1" 200 -]
[2023-10-15 13:57:13,791: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FAC6778F40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-15 13:57:13,806: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:57:13] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 13:57:29,166: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FAC80B18A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-15 13:57:29,181: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 13:57:29] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 16:09:14,371: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 16:09:14,376: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 16:09:30,210: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 16:09:30] "GET / HTTP/1.1" 200 -]
[2023-10-15 16:09:46,560: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 16:09:46] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 16:10:38,334: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 16:10:38,345: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:10:38,355: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:10:38,360: INFO: common: created directory at: artifacts]
[2023-10-15 16:10:38,365: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:10:38,370: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-15 16:11:23,232: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 16:11:23,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:11:23,270: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:11:23,285: INFO: common: created directory at: artifacts]
[2023-10-15 16:11:23,290: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:12:12,493: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1F5C:5E15C:1110F3:1E0CE9:652BC1E3
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 10:41:40 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100031-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1697366500.605034,VS0,VE1284
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 7de226fb60c8ff5b5dfdc34d5c6b9167516b38c7
Expires: Sun, 15 Oct 2023 10:46:40 GMT
Source-Age: 1

]
[2023-10-15 16:12:17,446: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 16:12:17,451: INFO: main: *******************]
[2023-10-15 16:12:17,482: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 16:12:17,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:12:17,527: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:12:17,537: INFO: common: created directory at: artifacts]
[2023-10-15 16:12:17,542: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 16:12:21,087: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 16:12:24,198: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 16:12:24,203: INFO: main: *******************]
[2023-10-15 16:12:24,203: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 16:12:24,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:12:24,213: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:12:24,233: INFO: common: created directory at: artifacts]
[2023-10-15 16:12:24,268: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:12:24,273: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:12:24,303: INFO: common: created directory at: artifacts\training]
[2023-10-15 16:16:37,356: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 16:16:37,361: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 16:17:17,029: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 16:17:17] "GET / HTTP/1.1" 200 -]
[2023-10-15 16:17:30,429: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\training\model.h5
[2023-10-15 16:17:30,488: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 16:17:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-15 16:21:58,094: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 16:21:58,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:21:58,124: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:21:58,129: INFO: common: created directory at: artifacts]
[2023-10-15 16:21:58,139: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:22:14,870: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1F5C:5E15C:1110F3:1E0CE9:652BC1E3
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 10:52:00 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100020-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1697367120.764459,VS0,VE265
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8cd7fcb05500266cdce03e44a4445747c76c7f36
Expires: Sun, 15 Oct 2023 10:57:00 GMT
Source-Age: 0

]
[2023-10-15 16:22:21,336: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 16:22:21,341: INFO: main: *******************]
[2023-10-15 16:22:21,351: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 16:22:21,366: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:22:21,396: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:22:21,401: INFO: common: created directory at: artifacts]
[2023-10-15 16:22:21,411: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 16:22:24,583: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 16:22:27,455: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 16:22:27,460: INFO: main: *******************]
[2023-10-15 16:22:27,460: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 16:22:27,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:22:27,505: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:22:27,518: INFO: common: created directory at: artifacts]
[2023-10-15 16:22:27,565: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:22:27,565: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:22:27,575: INFO: common: created directory at: artifacts\training]
[2023-10-15 16:36:57,822: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 16:36:57,836: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:36:57,841: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:36:57,841: INFO: common: created directory at: artifacts]
[2023-10-15 16:36:57,846: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:36:57,846: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-15 16:37:04,457: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 16:37:04,477: INFO: main: *******************]
[2023-10-15 16:37:04,507: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 16:37:04,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:37:04,617: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:37:04,633: INFO: common: created directory at: artifacts]
[2023-10-15 16:37:04,658: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 16:37:08,671: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 16:37:10,041: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 16:37:10,041: INFO: main: *******************]
[2023-10-15 16:37:10,041: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 16:37:10,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:37:10,056: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:37:10,071: INFO: common: created directory at: artifacts]
[2023-10-15 16:37:10,076: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:37:10,081: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:37:10,091: INFO: common: created directory at: artifacts\training]
[2023-10-15 16:39:12,836: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:39:12,848: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:39:12,853: INFO: common: created directory at: artifacts]
[2023-10-15 16:39:12,858: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:39:12,858: INFO: 1170291011: File already exists of size: ~ 20642 KB]
[2023-10-15 16:40:10,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:40:10,393: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:40:10,398: INFO: common: created directory at: artifacts]
[2023-10-15 16:40:10,398: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:40:10,408: INFO: 1170291011: File already exists of size: ~ 20642 KB]
[2023-10-15 16:41:02,018: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:41:02,028: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:41:02,033: INFO: common: created directory at: artifacts]
[2023-10-15 16:41:02,038: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:41:02,038: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:41:02,125: INFO: common: created directory at: artifacts\training]
[2023-10-15 16:44:53,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:44:53,691: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:44:53,701: INFO: common: created directory at: artifacts]
[2023-10-15 16:44:53,701: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:44:53,711: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:44:53,731: INFO: common: created directory at: artifacts\training]
[2023-10-15 16:48:41,946: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 16:48:41,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:48:41,962: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:48:41,970: INFO: common: created directory at: artifacts]
[2023-10-15 16:48:41,970: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:48:56,385: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1F5C:5E15C:1110F3:1E0CE9:652BC1E3
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 11:18:43 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100024-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1697368724.649744,VS0,VE266
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: befb54cc02b39e2ce5de6b65c00e18631a5f3999
Expires: Sun, 15 Oct 2023 11:23:43 GMT
Source-Age: 0

]
[2023-10-15 16:48:59,941: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 16:48:59,941: INFO: main: *******************]
[2023-10-15 16:48:59,941: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 16:48:59,941: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:48:59,957: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:48:59,957: INFO: common: created directory at: artifacts]
[2023-10-15 16:48:59,957: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 16:49:02,796: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 16:49:05,359: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 16:49:05,359: INFO: main: *******************]
[2023-10-15 16:49:05,359: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 16:49:05,383: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:49:05,407: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:49:05,453: INFO: common: created directory at: artifacts]
[2023-10-15 16:49:05,469: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:49:05,483: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:49:05,491: INFO: common: created directory at: artifacts\training]
[2023-10-15 16:51:26,404: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 16:51:26,410: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:51:26,440: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:51:26,445: INFO: common: created directory at: artifacts]
[2023-10-15 16:51:26,448: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 16:51:39,140: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1F5C:5E15C:1110F3:1E0CE9:652BC1E3
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 11:21:28 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100022-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1697368889.598893,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1d3fbbb14016eae2d7cdaecf192e12d6c2769aa6
Expires: Sun, 15 Oct 2023 11:26:28 GMT
Source-Age: 165

]
[2023-10-15 16:51:43,850: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 16:51:43,855: INFO: main: *******************]
[2023-10-15 16:51:43,858: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 16:51:43,860: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:51:43,870: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:51:43,875: INFO: common: created directory at: artifacts]
[2023-10-15 16:51:43,890: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 16:51:46,085: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 16:51:47,230: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 16:51:47,230: INFO: main: *******************]
[2023-10-15 16:51:47,230: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 16:51:47,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 16:51:47,248: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 16:51:47,250: INFO: common: created directory at: artifacts]
[2023-10-15 16:51:47,276: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 16:51:47,278: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 16:51:47,300: INFO: common: created directory at: artifacts\training]
[2023-10-15 18:27:59,191: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 18:27:59,208: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 18:29:15,105: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 18:29:15] "GET / HTTP/1.1" 200 -]
[2023-10-15 18:29:31,281: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\training\model.h5
[2023-10-15 18:29:31,334: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 18:29:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-15 18:31:11,031: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 18:31:11,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:31:11,072: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:31:11,072: INFO: common: created directory at: artifacts]
[2023-10-15 18:31:11,072: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 18:31:34,322: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 61BC:42EAB:119F1E:1F072F:652BE298
Accept-Ranges: bytes
Date: Sun, 15 Oct 2023 13:01:14 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100024-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1697374873.896916,VS0,VE1248
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b732a539be9f7e1dd4f86816e3b9330775781885
Expires: Sun, 15 Oct 2023 13:06:14 GMT
Source-Age: 1

]
[2023-10-15 18:31:37,831: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 18:31:37,831: INFO: main: *******************]
[2023-10-15 18:31:37,831: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 18:31:37,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:31:37,850: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:31:37,856: INFO: common: created directory at: artifacts]
[2023-10-15 18:31:37,872: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 18:31:39,842: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 18:31:42,508: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 18:31:42,508: INFO: main: *******************]
[2023-10-15 18:31:42,508: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 18:31:42,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:31:42,542: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:31:42,546: INFO: common: created directory at: artifacts]
[2023-10-15 18:31:42,555: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 18:31:42,555: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 18:31:42,577: INFO: common: created directory at: artifacts\training]
[2023-10-15 18:34:36,396: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 18:34:36,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:34:36,414: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:34:36,417: INFO: common: created directory at: artifacts]
[2023-10-15 18:34:36,419: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 18:34:36,421: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-15 18:34:39,106: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 18:34:39,106: INFO: main: *******************]
[2023-10-15 18:34:39,121: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 18:34:39,121: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:34:39,134: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:34:39,139: INFO: common: created directory at: artifacts]
[2023-10-15 18:34:39,156: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 18:34:40,908: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 18:34:43,763: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 18:34:43,763: INFO: main: *******************]
[2023-10-15 18:34:43,763: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 18:34:43,763: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:34:43,782: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:34:43,784: INFO: common: created directory at: artifacts]
[2023-10-15 18:34:43,786: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 18:34:43,788: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 18:34:43,805: INFO: common: created directory at: artifacts\training]
[2023-10-15 18:48:08,224: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-15 18:48:08,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:48:08,243: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:48:08,245: INFO: common: created directory at: artifacts]
[2023-10-15 18:48:08,247: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-15 18:48:08,249: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-15 18:48:13,972: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-15 18:48:13,987: INFO: main: *******************]
[2023-10-15 18:48:14,037: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-15 18:48:14,067: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:48:14,112: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:48:14,119: INFO: common: created directory at: artifacts]
[2023-10-15 18:48:14,167: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-15 18:48:17,961: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 18:48:19,574: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-15 18:48:19,574: INFO: main: *******************]
[2023-10-15 18:48:19,574: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-15 18:48:19,574: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 18:48:19,594: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 18:48:19,597: INFO: common: created directory at: artifacts]
[2023-10-15 18:48:19,599: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-15 18:48:19,601: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-15 18:48:19,616: INFO: common: created directory at: artifacts\training]
[2023-10-15 19:11:21,850: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-10-15 19:11:21,881: INFO: main: *******************]
[2023-10-15 19:11:21,881: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-10-15 19:11:21,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 19:11:21,942: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 19:11:21,951: INFO: common: created directory at: artifacts]
[2023-10-15 19:18:25,658: INFO: common: json file saved at: scores.json]
[2023-10-15 19:18:25,666: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-10-15 19:19:28,530: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 19:19:28,547: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 19:19:37,656: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:19:37] "GET / HTTP/1.1" 200 -]
[2023-10-15 19:19:50,572: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:19:50] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:20:03,091: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:20:03] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:20:16,290: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:20:16] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:23:09,091: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:23:09] "GET / HTTP/1.1" 200 -]
[2023-10-15 19:23:19,695: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:23:19] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:23:30,473: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001EBE24B3C40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-15 19:23:30,490: INFO: _internal: 192.168.0.121 - - [15/Oct/2023 19:23:30] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:24:15,540: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-15 19:24:15,540: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-15 19:24:25,178: INFO: _internal: 127.0.0.1 - - [15/Oct/2023 19:24:25] "GET / HTTP/1.1" 200 -]
[2023-10-15 19:24:43,600: INFO: _internal: 127.0.0.1 - - [15/Oct/2023 19:24:43] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:24:55,898: INFO: _internal: 127.0.0.1 - - [15/Oct/2023 19:24:55] "POST /predict HTTP/1.1" 200 -]
[2023-10-15 19:25:10,682: INFO: _internal: 127.0.0.1 - - [15/Oct/2023 19:25:10] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:03:39,723: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-16 12:03:39,725: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-16 12:03:47,273: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:03:47] "GET / HTTP/1.1" 200 -]
[2023-10-16 12:04:01,982: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:04:01] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:04:14,655: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:04:14] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:04:27,129: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:04:27] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:04:40,495: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:04:40] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:04:47,044: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001A60EF67880> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-16 12:04:47,066: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:04:47] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:04:59,061: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001A60F19B9C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-16 12:04:59,076: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:04:59] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:05:15,107: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:05:15] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:16:25,534: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-16 12:16:25,535: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-16 12:16:32,276: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:16:32] "GET / HTTP/1.1" 200 -]
[2023-10-16 12:23:47,756: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-16 12:23:47,760: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-16 12:24:54,140: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:24:54] "GET / HTTP/1.1" 200 -]
[2023-10-16 12:25:07,909: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:25:07] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:25:26,101: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:25:26] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:26:14,275: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:26:14] "GET / HTTP/1.1" 200 -]
[2023-10-16 12:26:24,729: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:26:24] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:27:07,775: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:27:07] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:27:10,836: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:27:10] "GET / HTTP/1.1" 200 -]
[2023-10-16 12:27:21,674: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E508A137E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-16 12:27:21,674: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:27:21] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 12:28:19,404: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-16 12:28:19,404: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-16 12:28:24,678: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:28:24] "GET / HTTP/1.1" 200 -]
[2023-10-16 12:28:37,984: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 12:28:37] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:49:03,371: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-16 19:49:03,373: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-16 19:49:24,192: INFO: _internal: 127.0.0.1 - - [16/Oct/2023 19:49:24] "GET / HTTP/1.1" 200 -]
[2023-10-16 19:49:42,550: INFO: _internal: 127.0.0.1 - - [16/Oct/2023 19:49:42] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:49:54,016: INFO: _internal: 127.0.0.1 - - [16/Oct/2023 19:49:54] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:50:48,223: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-16 19:50:48,227: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-16 19:56:45,163: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:56:45] "GET / HTTP/1.1" 200 -]
[2023-10-16 19:57:00,239: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:57:00] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:57:15,071: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:57:15] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:57:28,490: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:57:28] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:57:47,235: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:57:47] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:57:58,167: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021EA31437E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-16 19:57:58,167: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:57:58] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:58:09,499: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021EA336F920> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-16 19:58:09,499: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:58:09] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 19:58:14,666: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 19:58:14] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 20:00:29,237: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 20:00:29] "POST /predict HTTP/1.1" 200 -]
[2023-10-16 20:00:42,332: INFO: _internal: 192.168.0.121 - - [16/Oct/2023 20:00:42] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 12:42:37,501: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 12:42:37,501: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 12:42:54,802: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 12:42:54] "GET / HTTP/1.1" 200 -]
[2023-10-17 12:45:36,684: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-17 12:45:36,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 12:45:36,699: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 12:45:36,702: INFO: common: created directory at: artifacts]
[2023-10-17 12:45:36,704: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-17 12:45:36,707: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-17 12:45:43,900: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-17 12:45:43,903: INFO: main: *******************]
[2023-10-17 12:45:43,907: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-17 12:45:43,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 12:45:43,988: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 12:45:43,991: INFO: common: created directory at: artifacts]
[2023-10-17 12:45:44,002: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-17 12:45:47,252: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-17 12:45:50,644: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-17 12:45:50,644: INFO: main: *******************]
[2023-10-17 12:45:50,644: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-17 12:45:50,672: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 12:45:50,678: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 12:45:50,684: INFO: common: created directory at: artifacts]
[2023-10-17 12:45:50,686: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-17 12:45:50,689: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-17 12:45:50,702: INFO: common: created directory at: artifacts\training]
[2023-10-17 13:08:19,368: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-10-17 13:08:19,383: INFO: main: *******************]
[2023-10-17 13:08:19,383: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-10-17 13:08:19,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:08:19,420: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:08:19,424: INFO: common: created directory at: artifacts]
[2023-10-17 13:15:01,750: INFO: common: json file saved at: scores.json]
[2023-10-17 13:15:01,750: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-10-17 13:19:08,031: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 13:19:08,031: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 13:19:32,839: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 13:19:32] "GET / HTTP/1.1" 200 -]
[2023-10-17 13:19:47,541: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 13:19:47] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 13:19:59,972: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 13:19:59] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 13:20:14,404: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 13:20:14] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 13:21:34,382: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-17 13:21:34,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:21:34,405: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:21:34,417: INFO: common: created directory at: artifacts]
[2023-10-17 13:21:34,425: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-17 13:21:45,168: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21137678
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "3018953fda39d25f745a547addfd47d653799e3f5dfaaeca8a1c3e778fc37d06"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5B1C:2CDDB0:2F588:4AD74:652E3D07
Accept-Ranges: bytes
Date: Tue, 17 Oct 2023 07:51:36 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100022-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1697529095.139770,VS0,VE1343
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 09c2b380fd82a2bf452188a212fc3d8eff53a94e
Expires: Tue, 17 Oct 2023 07:56:36 GMT
Source-Age: 1

]
[2023-10-17 13:21:50,264: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-17 13:21:50,280: INFO: main: *******************]
[2023-10-17 13:21:50,291: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-17 13:21:50,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:21:50,364: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:21:50,364: INFO: common: created directory at: artifacts]
[2023-10-17 13:21:50,414: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-17 13:21:53,191: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-17 13:21:56,311: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-17 13:21:56,311: INFO: main: *******************]
[2023-10-17 13:21:56,311: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-17 13:21:56,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:21:56,339: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:21:56,348: INFO: common: created directory at: artifacts]
[2023-10-17 13:21:56,381: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-17 13:21:56,384: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-17 13:21:56,405: INFO: common: created directory at: artifacts\training]
[2023-10-17 13:23:13,569: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-17 13:23:13,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:23:13,598: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:23:13,599: INFO: common: created directory at: artifacts]
[2023-10-17 13:23:13,602: INFO: common: created directory at: artifacts/data_ingestion]
[2023-10-17 13:23:13,603: INFO: data_ingestion: File already exists of size: ~ 20642 KB]
[2023-10-17 13:23:19,562: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-17 13:23:19,578: INFO: main: *******************]
[2023-10-17 13:23:19,578: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-10-17 13:23:19,578: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:23:19,592: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:23:19,594: INFO: common: created directory at: artifacts]
[2023-10-17 13:23:19,596: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-10-17 13:23:23,070: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-17 13:23:24,135: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-10-17 13:23:24,137: INFO: main: *******************]
[2023-10-17 13:23:24,137: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-10-17 13:23:24,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-17 13:23:24,157: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-17 13:23:24,159: INFO: common: created directory at: artifacts]
[2023-10-17 13:23:24,161: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-10-17 13:23:24,163: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-10-17 13:23:24,172: INFO: common: created directory at: artifacts\training]
[2023-10-17 14:47:21,152: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 14:47:21,162: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 14:47:29,606: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:47:29] "GET / HTTP/1.1" 200 -]
[2023-10-17 14:47:49,411: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
[2023-10-17 14:47:49,494: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:47:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 14:50:19,400: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 14:50:19,400: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 14:50:29,533: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:50:29] "GET / HTTP/1.1" 200 -]
[2023-10-17 14:50:44,078: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
[2023-10-17 14:50:44,094: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:50:44] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 14:52:19,242: INFO: _internal: 127.0.0.1 - - [17/Oct/2023 14:52:19] "GET / HTTP/1.1" 200 -]
[2023-10-17 14:52:34,430: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
[2023-10-17 14:52:34,485: INFO: _internal: 127.0.0.1 - - [17/Oct/2023 14:52:34] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 14:54:29,874: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 14:54:29,877: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 14:54:39,781: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:54:39] "GET / HTTP/1.1" 200 -]
[2023-10-17 14:54:51,637: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
[2023-10-17 14:54:51,661: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:54:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 14:56:51,768: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 14:56:51,768: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 14:57:07,982: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:57:07] "GET / HTTP/1.1" 200 -]
[2023-10-17 14:57:16,576: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at model.h5
[2023-10-17 14:57:16,618: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 14:57:16] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 17:39:39,367: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 17:39:39,377: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 17:39:53,281: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 17:39:53] "GET / HTTP/1.1" 200 -]
[2023-10-17 17:40:57,513: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\training\model.h5
[2023-10-17 17:40:57,566: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 17:40:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 17:42:27,430: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 17:42:27,442: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 17:42:43,841: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 17:42:43] "GET / HTTP/1.1" 200 -]
[2023-10-17 17:42:55,811: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ML Projects\Potato-Leaf-Desease-End2End\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\anaconda3\envs\leaf_desease_detection\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
[2023-10-17 17:42:55,881: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 17:42:55] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-17 18:14:17,014: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 18:14:17,025: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 18:14:22,960: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:14:22] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:14:41,347: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:14:41] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:15:02,546: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:15:02] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:15:31,994: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:15:31] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:15:34,651: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:15:34] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:15:49,101: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:15:49] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:16:24,855: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:16:24] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:16:38,729: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001F9A6971A80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-17 18:16:38,737: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:16:38] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:17:41,142: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:17:41] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:17:54,773: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001F9A68DBB00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-17 18:17:54,781: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:17:54] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:18:14,021: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:18:14] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:18:36,035: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:18:36] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:18:59,818: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:18:59] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:19:20,165: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:19:20] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:20:14,577: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 18:20:14,577: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 18:23:00,718: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:23:00] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:23:20,794: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:23:20] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:23:34,409: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:23:34] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:23:56,148: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:23:56] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:24:24,221: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:24:24] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:25:05,718: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021162CE19E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-17 18:25:05,734: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:25:05] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:25:35,898: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021162C4BCE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-17 18:25:35,906: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:25:35] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:25:48,464: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:25:48] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:25:59,963: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:25:59] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:26:13,794: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:26:13] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:26:46,664: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:26:46] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:27:01,308: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:27:01] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:27:17,506: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:27:17] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:28:15,301: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.121:80]
[2023-10-17 18:28:15,301: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-17 18:28:31,779: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:28:31] "GET / HTTP/1.1" 200 -]
[2023-10-17 18:28:44,290: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:28:44] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:29:04,430: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:29:04] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:29:20,929: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:29:20] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:29:39,878: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:29:39] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:30:33,140: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002463711CEA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-17 18:30:33,140: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:30:33] "POST /predict HTTP/1.1" 200 -]
[2023-10-17 18:30:59,904: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000024634CF2AC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-10-17 18:30:59,904: INFO: _internal: 192.168.0.121 - - [17/Oct/2023 18:30:59] "POST /predict HTTP/1.1" 200 -]
